<?php
// sitemap.xml.php
// The site's single XML sitemap, generated by PHP on each request and served
// at /sitemap.xml via an .htaccess rewrite.
//
// The URL list itself lives in sitemap_urls.php so it can be shared with
// cron/indexnow_submit.php. This file only turns that list into XML.

require_once __DIR__ . '/db_connect.php';
require_once __DIR__ . '/sitemap_urls.php';

header('Content-Type: application/xml; charset=utf-8');

$urls = sitemap_build_urls();

echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";
foreach ($urls as $u) {
    echo "  <url>\n";
    echo "    <loc>" . htmlspecialchars($u['loc']) . "</loc>\n";
    if (!empty($u['lastmod'])) {
        echo "    <lastmod>" . htmlspecialchars($u['lastmod']) . "</lastmod>\n";
    }
    if (!empty($u['changefreq'])) {
        echo "    <changefreq>" . htmlspecialchars($u['changefreq']) . "</changefreq>\n";
    }
    echo "    <priority>" . htmlspecialchars($u['priority']) . "</priority>\n";
    echo "  </url>\n";
}
echo '</urlset>' . "\n";
