<?php
// sitemap.xml.php
// The site's single XML sitemap, generated by PHP on each request and served
// at /sitemap.xml via an .htaccess rewrite.
//
// Everything lives here so there is one URL to submit to Search Console / Bing
// and nothing to hand-maintain: core pages carry real <lastmod> values from
// their file modification times, and the feature / compare / industry / invoice
// / article sections are discovered from the filesystem so new pages appear
// automatically.

require_once __DIR__ . '/db_connect.php';

header('Content-Type: application/xml; charset=utf-8');

$urls = [];

/**
 * Queue one sitemap entry. <lastmod> is taken from $file's modification time
 * when the file exists; entries whose source file is missing are skipped so we
 * never advertise a dead URL.
 */
function add_url(array &$urls, string $loc, ?string $file, string $priority, ?string $changefreq = null): void
{
    if ($file !== null && !file_exists($file)) {
        return;
    }
    $entry = ['loc' => $loc, 'priority' => $priority];
    if ($file !== null) {
        $entry['lastmod'] = date('Y-m-d', filemtime($file));
    }
    if ($changefreq !== null) {
        $entry['changefreq'] = $changefreq;
    }
    $urls[] = $entry;
}

// --- Core marketing pages (curated: priority + change frequency by hand) ---
$corePages = [
    ['/',                'index.php',                '1.0', 'weekly'],
    ['/downloads/',      'downloads/index.php',      '1.0', 'weekly'],
    ['/features/',       'features/index.php',       '0.9', 'monthly'],
    ['/pricing/',        'pricing/index.php',        '0.9', 'monthly'],
    ['/documentation/',  'documentation/index.php',  '0.9', 'weekly'],
    ['/about-us/',       'about-us/index.php',       '0.9', 'monthly'],
    ['/who-its-for/',    'who-its-for/index.php',    '0.8', 'monthly'],
    ['/contact-us/',     'contact-us/index.php',     '0.8', 'monthly'],
    ['/whats-new/',      'whats-new/index.php',      '0.7', 'weekly'],
    ['/community/',      'community/index.php',      '0.6', 'daily'],
    ['/older-versions/', 'older-versions/index.php', '0.5', 'monthly'],
    ['/review/',         'review/index.php',         '0.5', 'monthly'],
];
foreach ($corePages as [$path, $file, $priority, $changefreq]) {
    add_url($urls, site_url($path), __DIR__ . '/' . $file, $priority, $changefreq);
}

// --- Auto-discovered page clusters ---
// Each child directory with an index.php becomes one URL, so adding a new
// feature / comparison / industry page needs no sitemap edit.
$clusters = [
    ['glob' => 'features/*/index.php', 'prefix' => '/features/',  'priority' => '0.8'],
    ['glob' => 'compare/*/index.php',  'prefix' => '/compare/',   'priority' => '0.8'],
];
foreach ($clusters as $cluster) {
    foreach (glob(__DIR__ . '/' . $cluster['glob']) as $file) {
        $slug = basename(dirname($file));
        add_url($urls, site_url($cluster['prefix'] . $slug . '/'), $file, $cluster['priority'], 'monthly');
    }
}

// Industry pages live at the root as /for-<industry>/.
foreach (glob(__DIR__ . '/for-*/index.php') as $file) {
    $slug = basename(dirname($file));
    add_url($urls, site_url('/' . $slug . '/'), $file, '0.8', 'monthly');
}

// --- Legal pages (served as .php, change rarely) ---
foreach (['privacy', 'terms', 'eula', 'refund'] as $doc) {
    add_url($urls, site_url('/legal/' . $doc . '.php'), __DIR__ . '/legal/' . $doc . '.php', '0.4', 'yearly');
}

// --- Free invoice generator tool + niche landing pages ---
add_url($urls, site_url('/invoice-generator/'), __DIR__ . '/invoice-generator/index.php', '0.9', 'monthly');
foreach (glob(__DIR__ . '/niches/data/*.php') as $file) {
    $slug = basename($file, '.php');
    if ($slug === '_template') continue;
    $data = require $file;
    $urlSlug = $data['slug'] ?? $slug;
    // Generic seed lives at /free-invoice-generator/ (no slug in the URL).
    $loc = $urlSlug === 'generic'
        ? site_url('/free-invoice-generator/')
        : site_url('/free-invoice-generator/' . $urlSlug . '/');
    add_url($urls, $loc, $file, $urlSlug === 'generic' ? '0.9' : '0.8', 'monthly');
}

// --- Invoice template library ---
add_url($urls, site_url('/invoice-template/'), __DIR__ . '/invoice-template/index.php', '0.8', 'monthly');
foreach (glob(__DIR__ . '/invoice-template/data/*.php') as $file) {
    $slug = basename($file, '.php');
    if ($slug === '_template') continue;
    $data = require $file;
    $urlSlug = $data['slug'] ?? $slug;
    $kind = $data['kind'] ?? 'style-format';
    // Format-generic pages rank slightly above style-format pages so Search
    // Console treats them as the cluster entry point.
    add_url($urls, site_url('/invoice-template/' . $urlSlug . '/'), $file, $kind === 'format-generic' ? '0.8' : '0.7', 'monthly');
}

// --- Articles: editorial hub + each guide ---
add_url($urls, site_url('/invoice-guides/'), __DIR__ . '/invoice-guides/index.php', '0.8', 'weekly');
foreach (glob(__DIR__ . '/articles/data/*.php') as $file) {
    $slug = basename($file, '.php');
    if ($slug === '_template') continue;
    $data = require $file;
    $urlSlug = $data['slug'] ?? $slug;
    add_url($urls, site_url('/' . $urlSlug . '/'), $file, '0.7', 'monthly');
}

echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";
foreach ($urls as $u) {
    echo "  <url>\n";
    echo "    <loc>" . htmlspecialchars($u['loc']) . "</loc>\n";
    if (isset($u['lastmod'])) {
        echo "    <lastmod>" . htmlspecialchars($u['lastmod']) . "</lastmod>\n";
    }
    if (isset($u['changefreq'])) {
        echo "    <changefreq>" . htmlspecialchars($u['changefreq']) . "</changefreq>\n";
    }
    echo "    <priority>" . htmlspecialchars($u['priority']) . "</priority>\n";
    echo "  </url>\n";
}
echo '</urlset>' . "\n";
