<?php
/**
 * Curated list of website domains we should NEVER outreach to.
 *
 * These are major Canadian (and a few US/global) brand-owner domains that
 * indicate the result is a corporate/franchise/government location rather
 * than a small independent business. A Google Places search for "travel
 * agencies in Saskatoon" can return the Air Canada Maple Leaf Lounge; its
 * site is aircanada.ca, and emailing aircanada.ca is a hard "no" for an
 * outreach pipeline targeting small business owners.
 *
 * Match rules (applied by filter_chain_domain in outreach_helpers.php):
 *   - exact host match: "aircanada.ca" matches  "aircanada.ca"
 *   - subdomain match:  "aircanada.ca" matches  "lounges.aircanada.ca"
 *   - TLD-suffix groups handle .gc.ca / .gov / .gov.uk / etc. uniformly
 *
 * Keep this list focused on the largest, clearest brands. False-positives
 * here cost a legit lead; false-negatives cost domain reputation. Aim for
 * "every Canadian has heard of this brand."
 *
 * Loaded once and cached by filter_chain_domain.
 */

return [
    // ─── Airlines (Canadian + major foreign carriers serving Canada) ───
    'aircanada.ca',
    'westjet.com',
    'flair.com', 'flyflair.com',
    'porterairlines.com',
    'aircanada.com',
    'transat.com', 'airtransat.com',
    'delta.com',
    'aa.com', 'americanairlines.com',
    'united.com',
    'southwest.com',
    'klm.com',
    'lufthansa.com',
    'britishairways.com',
    'emirates.com',

    // ─── Major Canadian banks + insurers ───
    'rbc.com', 'rbcroyalbank.com',
    'td.com', 'tdcanadatrust.com', 'tdbank.com',
    'scotiabank.com',
    'bmo.com',
    'cibc.com',
    'nbc.ca', 'nbcfinance.com', 'nationalbank.ca',
    'desjardins.com',
    'tangerine.ca',
    'simplii.com',
    'eqbank.ca',
    'manulife.com', 'manulife.ca',
    'sunlife.ca', 'sunlife.com',
    'canadalife.com',
    'greatwestlife.com',
    'wawanesa.com',
    'intact.ca',
    'tdinsurance.com',

    // ─── Telcos / cable / internet ───
    'bell.ca', 'bellmedia.ca',
    'rogers.com', 'rogers.ca',
    'telus.com',
    'shaw.ca',
    'koodomobile.com',
    'fido.ca',
    'virginplus.ca',
    'freedommobile.ca',
    'sasktel.com', 'sasktel.ca',
    'mts.ca',
    'videotron.com',
    'eastlink.ca',

    // ─── Big-box / national retailers ───
    'walmart.ca', 'walmart.com',
    'costco.ca', 'costco.com',
    'canadiantire.ca',
    'sportchek.ca',
    'marks.com', 'markswork.com',
    'homedepot.ca', 'homedepot.com',
    'lowes.ca', 'lowes.com',
    'rona.ca',
    'homehardware.ca',
    'staples.ca', 'staples.com',
    'bestbuy.ca', 'bestbuy.com',
    'thebay.com', 'hbc.com',
    'winners.ca',
    'marshalls.ca',
    'homesense.ca',
    'dollarama.com',
    'shoppersdrugmart.ca',
    'londondrugs.com',
    'rexall.ca',
    'pharmaprix.ca',
    'loblaws.ca',
    'realcanadiansuperstore.ca',
    'sobeys.com',
    'safeway.ca',
    'metro.ca',
    'freshco.com',
    'iga.net', 'iga.ca',
    'saveonfoods.com',
    'foodbasics.ca',
    'no-frills.ca', 'nofrills.ca',
    'farmboy.ca',
    'longos.com',

    // ─── Fast food / coffee chains ───
    'tims.ca', 'timhortons.com', 'timhortons.ca',
    'mcdonalds.com', 'mcdonalds.ca',
    'starbucks.com', 'starbucks.ca',
    'subway.com',
    'pizzapizza.ca',
    'pizzahut.ca', 'pizzahut.com',
    'dominos.ca', 'dominos.com',
    'kfc.ca', 'kfc.com',
    'wendys.com',
    'burgerking.com', 'burgerking.ca',
    'a-w.ca', 'aw.ca', 'aw.com',
    'harveys.ca',
    'swisschalet.com',
    'boostonjuice.com', 'boosterjuice.com',
    'secondcup.com', 'secondcup.ca',
    'mrsub.ca',
    'whitespot.ca',
    'whitespot.com',
    'jugojuice.com',
    'taco-bell.com', 'tacobell.com',

    // ─── Oil / gas / utilities ───
    'petrocanada.ca', 'petro-canada.ca',
    'esso.ca', 'esso.com',
    'shell.ca', 'shell.com',
    'husky.ca', 'huskyenergy.com',
    'cenovus.com',
    'suncor.com',
    'enbridge.com',
    'tcenergy.com',
    'fortisbc.com',
    'enmax.com',
    'epcor.com',
    'saskpower.com',
    'saskenergy.com',
    'manitobahydro.ca', 'hydro.mb.ca',
    'bchydro.com',
    'hydroquebec.com',
    'hydroone.com',

    // ─── Hotels / hospitality chains ───
    'marriott.com',
    'hilton.com',
    'ihg.com', 'holidayinn.com',
    'hyatt.com',
    'fairmont.com',
    'choicehotels.com',
    'wyndhamhotels.com',
    'bestwestern.com',
    'sandman.ca', 'sandmanhotels.com',
    'deltahotels.com',
    'expedia.ca', 'expedia.com',
    'booking.com',
    'trivago.ca', 'trivago.com',
    'airbnb.ca', 'airbnb.com',

    // ─── Auto / rental ───
    'enterprise.ca', 'enterprise.com',
    'hertz.ca', 'hertz.com',
    'avis.ca', 'avis.com',
    'budget.ca', 'budget.com',
    'discountcar.com',
    'national-car.com',
    'toyota.ca', 'toyota.com',
    'honda.ca', 'honda.com',
    'ford.ca', 'ford.com',
    'gm.ca', 'gm.com', 'chevrolet.ca',
    'kia.ca', 'kia.com',
    'hyundai.ca', 'hyundai.com',
    'nissan.ca', 'nissan.com',
    'mazda.ca', 'mazda.com',
    'bmw.ca', 'bmw.com',
    'mercedes-benz.ca', 'mbusa.com',
    'audi.ca', 'audi.com',
    'volkswagen.ca', 'vw.com',
    'tesla.com',

    // ─── Big tech / SaaS / streaming ───
    'amazon.ca', 'amazon.com',
    'apple.ca', 'apple.com',
    'google.ca', 'google.com',
    'microsoft.ca', 'microsoft.com',
    'facebook.com', 'meta.com',
    'netflix.com',
    'disneyplus.com',
    'spotify.com',
    'paypal.ca', 'paypal.com',
    'stripe.com',
    'square.com',
    'intuit.ca', 'intuit.com', 'quickbooks.com',
    'xero.com',
    'freshbooks.com',
    'shopify.com',
    'wave.com', 'waveapps.com',
    'zoom.us',

    // ─── Couriers / logistics ───
    'canadapost.ca', 'canadapost-postescanada.ca',
    'purolator.com',
    'fedex.com', 'fedex.ca',
    'ups.com',
    'dhl.com',
    'cn.ca',
    'cpr.ca', 'canadianpacific.com',

    // ─── Government, education, healthcare (federal/provincial) ───
    'canada.ca', 'gc.ca',
    'saskatchewan.ca',
    'alberta.ca', 'gov.ab.ca',
    'gov.mb.ca', 'manitoba.ca',
    'ontario.ca', 'gov.on.ca',
    'quebec.ca', 'gouv.qc.ca',
    'bc.ca', 'gov.bc.ca',
    'gnb.ca',
    'novascotia.ca',
    'gov.pe.ca',
    'gov.nl.ca',
    'cra-arc.gc.ca',
    'rcmp-grc.gc.ca',
    'saskatoon.ca',
    'regina.ca',
    'calgary.ca',
    'edmonton.ca',
    'winnipeg.ca',
    'vancouver.ca',
    'toronto.ca',
    'ottawa.ca',
    'usask.ca',
    'uregina.ca',
    'ualberta.ca',
    'ucalgary.ca',
    'ubc.ca',
    'utoronto.ca',
    'mcgill.ca',
    'concordia.ca',
    'yorku.ca',
    'umanitoba.ca',
    'queensu.ca',
    'mun.ca',
    'dal.ca',

    // ─── User-flagged: previously generated bad leads ───
    'skillsamurai.com',
    'skillsamuraiportal.com',
];
