<?php
// invoice-template/data/word.php
// /invoice-template/word/ format-generic landing page.

return [
  'slug' => 'word',
  'kind' => 'format-generic',
  'style' => null,
  'format' => 'word',

  'h1' => 'Free Word invoice templates',
  'meta_title' => 'Free Word Invoice Templates (.docx) | Argo Books',
  'meta_description' => 'Free Microsoft Word invoice templates in five styles. Download as .docx, edit in Word or Google Docs. No signup, no watermark.',

  'intro_html' => '<p>Word templates are the easiest way to edit an invoice after the fact. Save the .docx, open it in Microsoft Word or Google Docs, change any text, save again. Pick a visual style below and you will land in the free invoice generator with that style preselected, ready to customize and download.</p>',

  'body_html' =>
    '<p>Every Word template on this page is generated by the same free invoice tool, so the layout, fonts, and totals math match the on-screen invoice. Open the .docx in Microsoft Word, LibreOffice Writer, Google Docs, or Apple Pages.</p>'
    . '<p>If you need pixel-exact visual fidelity to the on-screen preview, choose a PDF template instead. Word documents reflow on different versions of Word, so headings and table widths may shift slightly between machines. For send-once-and-forget invoices, PDF is the safer choice. For invoices you expect to edit, Word is more flexible.</p>',

  'faqs' => [
    ['q' => 'Will these Word templates open in Google Docs?', 'a' => 'Yes. Upload the .docx to Google Drive and double click to open in Google Docs. Some fonts may swap to a Google-hosted equivalent.'],
    ['q' => 'Are macros required to use these templates?', 'a' => 'No. The Word templates contain plain text, tables, and formatting only. No macros, no scripts, no embedded objects.'],
    ['q' => 'Can I edit the totals in Word?', 'a' => 'Yes, but the totals are plain numbers, not Excel-style formulas. If you want auto-calculating totals, choose an Excel or Google Sheets template instead.'],
    ['q' => 'Why is the Word template not pixel-identical to the on-screen preview?', 'a' => 'Word reflows content based on the system fonts and document margins. The generator picks the closest match available. For pixel-exact output, use a PDF template.'],
  ],

  'related_slugs' => ['pdf', 'google-docs', 'classic-word', 'modern-word', 'formal-word', 'elegant-word', 'ribbon-word'],
];
