<?php
// invoice-template/data/word.php
// /invoice-template/word/ format-generic landing page.

return [
  'slug' => 'word',
  'kind' => 'format-generic',
  'style' => null,
  'format' => 'word',

  'h1' => 'Free Word invoice templates',
  'meta_title' => 'Free Word Invoice Templates (.docx) | Argo Books',
  'meta_description' => 'Free Microsoft Word invoice templates in five styles. Download as .docx, edit in Word or Google Docs. No signup, no watermark.',

  'intro_html' => '<p>Word templates are the easiest way to edit an invoice after the fact. Save the .docx, open it in Microsoft Word or Google Docs, change any text, save again. Pick a visual style below and you will land in the free invoice generator with that style preselected, ready to customize and download.</p>',

  'body_html' =>
    '<p>Every Word template on this page is generated by the same free invoice tool, so the layout, fonts, and totals math match the on-screen invoice. Open the .docx in Microsoft Word, LibreOffice Writer, Google Docs, or Apple Pages.</p>'
    . '<p>If you need pixel-exact visual fidelity to the on-screen preview, choose a PDF template instead. Word documents reflow on different versions of Word, so headings and table widths may shift slightly between machines. For send-once-and-forget invoices, PDF is the safer choice. For invoices you expect to edit, Word is more flexible.</p>'

    . '<h3>What to include on a Word invoice</h3>'
    . '<p>A complete invoice leaves no question about who owes what, and by when. Every Word invoice template here already has a place for each of these, so you just fill in the blanks:</p>'
    . '<ul>'
    . '<li><strong>Your business details.</strong> Name, address, email, phone, and a logo if you have one.</li>'
    . '<li><strong>The word "Invoice" and a unique invoice number.</strong> A clear number keeps your records straight and makes follow-up easy. See <a href="/invoice-numbering-best-practices/">invoice numbering best practices</a> if you are starting from scratch.</li>'
    . '<li><strong>The client\'s name and address.</strong> Bill the right person or company, spelled the way they expect.</li>'
    . '<li><strong>Invoice date and due date.</strong> State the payment terms so "due on receipt" or "net 30" is never ambiguous.</li>'
    . '<li><strong>An itemized list.</strong> One line per product or service, with quantity, rate, and line total.</li>'
    . '<li><strong>Subtotal, tax, and total due.</strong> Show tax on its own line so the math is easy to check.</li>'
    . '<li><strong>Payment instructions.</strong> How you want to be paid, plus any late-fee terms.</li>'
    . '</ul>'
    . '<p>Not sure what belongs on yours? Our guide on <a href="/what-to-include-on-an-invoice/">what to include on an invoice</a> walks through every field in plain language.</p>'

    . '<h3>How to use these Word invoice templates</h3>'
    . '<p>No signup, no watermark. Going from blank template to a finished invoice in Word takes four steps:</p>'
    . '<ol>'
    . '<li>Pick a visual style below. You land in the free invoice generator with that style preselected.</li>'
    . '<li>Fill in your business details, the client, and the line items. The totals calculate as you type.</li>'
    . '<li>Download as a Word .docx, or switch to PDF if you would rather send a locked file.</li>'
    . '<li>Open the .docx in Microsoft Word, Google Docs, LibreOffice, or Apple Pages for any final edits, then send it.</li>'
    . '</ol>'
    . '<p>Because the file is a plain .docx, you can save it as your own reusable starting point and change only the client and line items next time.</p>'

    . '<h3>Word, PDF, or Excel: which format to choose</h3>'
    . '<p>All three are free here, and the right one depends on what you need the invoice to do:</p>'
    . '<ul>'
    . '<li><strong>Word</strong> is best when you expect to edit the invoice after downloading, or want a blank template you can reuse.</li>'
    . '<li><strong><a href="/invoice-template/pdf/">PDF</a></strong> is best for sending. It looks identical on every device and cannot be changed by accident.</li>'
    . '<li><strong><a href="/invoice-template/excel/">Excel</a></strong> is best when you want totals to auto-calculate with built-in formulas.</li>'
    . '</ul>',

  'faqs' => [
    ['q' => 'Will these Word templates open in Google Docs?', 'a' => 'Yes. Upload the .docx to Google Drive and double click to open in Google Docs. Some fonts may swap to a Google-hosted equivalent.'],
    ['q' => 'Are macros required to use these templates?', 'a' => 'No. The Word templates contain plain text, tables, and formatting only. No macros, no scripts, no embedded objects.'],
    ['q' => 'Can I edit the totals in Word?', 'a' => 'Yes, but the totals are plain numbers, not Excel-style formulas. If you want auto-calculating totals, choose an Excel or Google Sheets template instead.'],
    ['q' => 'Why is the Word template not pixel-identical to the on-screen preview?', 'a' => 'Word reflows content based on the system fonts and document margins. The generator picks the closest match available. For pixel-exact output, use a PDF template.'],
  ],

  'related_slugs' => ['pdf', 'google-docs', 'classic-word', 'modern-word', 'formal-word', 'elegant-word', 'ribbon-word'],
];
